-- Add missing columns to LOAN table
ALTER TABLE LOAN
ADD COLUMN Interest_Rate DECIMAL(5, 2) NOT NULL DEFAULT 8.5,
ADD COLUMN Term INT NOT NULL DEFAULT 20,
ADD COLUMN Type VARCHAR(50) NOT NULL DEFAULT 'Personal',
ADD COLUMN Purpose VARCHAR(100) NOT NULL DEFAULT 'General',
ADD COLUMN Status VARCHAR(20) NOT NULL DEFAULT 'Pending',
ADD COLUMN Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Add missing columns to LOAN_ACCOUNT table
ALTER TABLE LOAN_ACCOUNT
ADD COLUMN Balance DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
ADD COLUMN Status VARCHAR(20) NOT NULL DEFAULT 'Active'; 