-- Drop and recreate LOAN_ACCOUNT table with correct structure
DROP TABLE IF EXISTS LOAN_ACCOUNT;

CREATE TABLE LOAN_ACCOUNT (
    Loan_ID INT,
    Type VARCHAR(20) NOT NULL,
    Balance DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    Status VARCHAR(20) NOT NULL DEFAULT 'Active',
    PRIMARY KEY (Loan_ID),
    FOREIGN KEY (Loan_ID) REFERENCES LOAN(Loan_ID) ON DELETE CASCADE
) ENGINE=InnoDB; 